# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - python: "pypy3.5"

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox


